/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:window1:653226:
  appc.background(230);
} //_CODE_:window1:653226:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:552448:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:552448:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:700607:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:700607:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:586885:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:586885:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  window1 = new GWindow(this, "Window title", 0, 0, 300, 200, false, JAVA2D);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1.papplet, 20, 20, 80, 20);
  label1.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label1.setText("Mode");
  label1.setOpaque(false);
  label2 = new GLabel(window1.papplet, 20, 70, 80, 20);
  label2.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label2.setText("Speed");
  label2.setOpaque(false);
  button1 = new GButton(window1.papplet, 110, 150, 80, 30);
  button1.setText("Start/Pause");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(window1.papplet, 40, 150, 50, 30);
  button2.setText("<");
  button2.setTextBold();
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(window1.papplet, 210, 150, 50, 30);
  button3.setText(">");
  button3.setTextBold();
  button3.addEventHandler(this, "button3_click1");
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label2; 
GButton button1; 
GButton button2; 
GButton button3; 

